# Generated by Django 2.2.3 on 2019-07-31 19:40

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code_melli', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('tarikh_tavalod', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'مرد'), (0, 'زن')], null=True)),
                ('father_name', models.CharField(blank=True, max_length=35, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shomare_hesab', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('shomare_cart', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('shomare_shaba', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('name_saheb_hesab', models.CharField(blank=True, max_length=80, null=True)),
                ('name_bank', models.CharField(blank=True, max_length=80, null=True)),
                ('code_posti', models.CharField(blank=True, max_length=10, null=True)),
                ('kife_pool', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999, message='کیف پول نمیتواند بیشتر از 9999999999 باشد. ')])),
                ('kife_daramad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999, message='کیف درآمد نمیتواند بیشتر از 9999999999 باشد. ')])),
                ('id_telegram', models.CharField(blank=True, max_length=30, null=True)),
                ('nooe_heshab', models.IntegerField(blank=True, choices=[(0, 'تبلیغ گذار'), (1, 'منتشر کننده'), (2, 'هر دو')], null=True)),
                ('vazeyat', models.IntegerField(blank=True, choices=[(1, 'فعال'), (0, 'غیرفعال')], null=True)),
                ('image_cart_melli', models.ImageField(blank=True, null=True, upload_to=system.functions.upload_cart_melli_path)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=system.functions.upload_avatar_path)),
                ('code_moaref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pelan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=80, unique=True)),
                ('gheymat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('tarikh_ijad', models.DateTimeField(auto_now_add=True)),
                ('tedad_click', models.IntegerField()),
                ('vazeyat', models.IntegerField(choices=[(1, 'فعال'), (0, 'غیرفعال')])),
            ],
        ),
        migrations.CreateModel(
            name='TanzimatPaye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=250, unique=True)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tabligh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('tarikh_ijad', models.DateTimeField(auto_now_add=True)),
                ('tedad_click', models.IntegerField()),
                ('tedad_click_shode', models.IntegerField(default=0)),
                ('vazeyat', models.IntegerField(choices=[(0, 'لغو شده'), (1, 'فعال'), (2, 'در انتظار تایید'), (3, 'به اتمام رسیده')])),
                ('code_pelan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Pelan')),
                ('code_tabligh_gozaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('tarikh', models.DateTimeField(auto_now_add=True)),
                ('ferestande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferestande_user_id', to=settings.AUTH_USER_MODEL)),
                ('girande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girande_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_user_id', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh', models.DateTimeField(default=datetime.datetime.now)),
                ('ip', models.CharField(max_length=15)),
                ('montasher_konande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tabligh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Tabligh')),
            ],
        ),
    ]
