# Generated by Django 2.2.3 on 2019-07-30 04:28

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code_melli', models.CharField(max_length=10, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('gender', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shomare_hesab', models.CharField(blank=True, max_length=30, null=True)),
                ('shomare_cart', models.CharField(blank=True, max_length=30, null=True)),
                ('shomare_shaba', models.CharField(blank=True, max_length=30, null=True)),
                ('name_saheb_hesab', models.CharField(blank=True, max_length=30, null=True)),
                ('name_bank', models.CharField(blank=True, max_length=30, null=True)),
                ('code_posti', models.CharField(blank=True, max_length=10, null=True)),
                ('kife_pool', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('kife_daramad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('code_moaref', models.CharField(blank=True, max_length=30, null=True)),
                ('tarikh_ozviyat', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('id_telegram', models.CharField(blank=True, max_length=30, null=True)),
                ('nooe_heshab', models.CharField(choices=[('تبلیغ گذار', 'تبلیغ گذار'), ('منتشر کننده', 'منتشر کننده'), ('هر دو', 'هر دو')], max_length=20)),
                ('vazeyat', models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال'), ('در انتظار', 'در انتظار')], max_length=20)),
                ('image_cart_melli', models.ImageField(blank=True, null=True, upload_to=system.functions.upload_cart_melli_path)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=system.functions.upload_avatar_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pelan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30, unique=True)),
                ('gheymat', models.IntegerField(default=500000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('tarikh_ijad', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('tedad_click', models.IntegerField(default=0)),
                ('vazeyat', models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال'), ('در انتظار', 'در انتظار')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tabligh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30, unique=True)),
                ('tarikh_ijad', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('tedad_click', models.IntegerField(blank=True, default=0, null=True)),
                ('tedad_click_shode', models.IntegerField(blank=True, default=0, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('vazeyat', models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال'), ('در انتظار', 'در انتظار')], max_length=10)),
                ('code_pelan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Pelan')),
                ('code_tabligh_gozaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarikh_click', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('code_montasher_konande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('code_tabligh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Tabligh')),
            ],
        ),
    ]
