# Generated by Django 2.2.3 on 2019-07-28 17:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelan',
            fields=[
                ('code_pelan', models.AutoField(primary_key=True, serialize=False)),
                ('onvan', models.CharField(max_length=30)),
                ('gheymat', models.IntegerField(default=500000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999)])),
                ('tarikh_ijad', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vazeyat', models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال'), ('در انتظار', 'در انتظار')], max_length=10)),
            ],
        ),
    ]
