# Generated by Django 2.2.3 on 2019-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelan',
            name='vazeyat',
            field=models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tabligh',
            name='vazeyat',
            field=models.CharField(choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='vazeyat',
            field=models.CharField(blank=True, choices=[('فعال', 'فعال'), ('غیرفعال', 'غیرفعال')], max_length=20, null=True),
        ),
    ]
