# Generated by Django 2.2.3 on 2019-08-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payam',
            name='vazeyat',
            field=models.IntegerField(choices=[(0, 'خوانده شده'), (1, 'خوانده نشده'), (2, 'ارسال شده')], default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sath',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pelan',
            name='vazeyat',
            field=models.IntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')]),
        ),
        migrations.AlterField(
            model_name='tabligh',
            name='vazeyat',
            field=models.IntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال'), (2, 'لغو شده'), (3, 'در انتظار تایید'), (4, 'به اتمام رسیده')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='vazeyat',
            field=models.IntegerField(blank=True, choices=[(0, 'غیرفعال'), (1, 'فعال')], null=True),
        ),
    ]
