# Generated by Django 2.2.3 on 2019-07-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190730_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanzimatPaye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
