# Generated by Django 2.2.3 on 2019-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190802_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'زن'), (1, 'مرد'), (2, 'نا مشخص')], default=3, null=True),
        ),
    ]
