# Generated by Django 2.2.3 on 2019-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_tanzimatpaye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanzimatpaye',
            name='onvan',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
